# Generated by Django 4.2.2 on 2023-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('ailment', models.CharField(max_length=100)),
                ('sla', models.CharField(max_length=100)),
                ('ptat', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('approvedAmount', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
